id: ICB1B073A
legacy_id: P009099
ocr_import_info:
  bdrc_scan_id: W1KG22061
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T21:59:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T12:53:51.816585+00:00'
last_modified: 2022-08-31 20:55:04.491700
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22061
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22061
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་བསྟན་བཅོས་རྒྱས་འགྲེལ།
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.8804894953782886
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG22099:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22099
      total_pages: 584
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22099.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8929288377736551
    legacy_id: v001
  I1KG22100:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22100
      total_pages: 570
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22100.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8679193136133944
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
