id: P009099
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22061
  title: ཤེར་ཕྱིན་མངོན་རྟོགས་རྒྱན་གྱི་བསྟན་བཅོས་རྒྱས་འགྲེལ།
  author: ''
  volumes:
    68a28a947cf947b28e1de7df6e0c585f:
      image_group_id: I1KG22099
      title: ''
      volume_number: 1
      total_pages: 584
      base_file: v001.txt
    e60a86fc318449cea4682763e10a83db:
      image_group_id: I1KG22100
      title: ''
      volume_number: 2
      total_pages: 570
      base_file: v002.txt
